services:
  - type: web
    name: wa-gemini-bot
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: GRAPH_API_VERSION
        value: v20.0
      - key: GEMINI_MODEL
        value: gemini-2.5-flash

      # secrets: isi di Render dashboard (jangan taruh value token di github)
      - key: VERIFY_TOKEN
        sync: false
      - key: WA_PHONE_NUMBER_ID
        sync: false
      - key: WA_ACCESS_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
